---
name: "Executive Thesis"
title: "WATER AGE, WATER CHEMISTRY, AND MICROBIAL POPULATIONS IN A DRINKING WATER DISTRIBUTION SYSTEM"
output:
  html_document: 
    theme: united
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    self_contained: true
    toc_sticky: false
    css: styles.css
baseurl: "/executiveThesis"  
---
# Executive Summary
::: fake-h2
WATER AGE, WATER CHEMISTRY, AND MICROBIAL POPULATIONS IN A DRINKING WATER DISTRIBUTION SYSTEM
:::
::: fake-h2
Under the Supervision of Professors James T. Waples, and Ryan J. Newton, PhDs\
The University of Wisconsin-Milwaukee, 2021\
:::

## Introduction

::: indent
Microbes in tap water play a crucial role in pipe corrosion, human health, and water aesthetics. Because instances of tap water borne illnesses are on the rise in the USA, and many water distribution systems are reaching the end of their design lifespan, research leading to a better understanding of microbial growth and colonization is being actively pursued by many labs (EPA 2002; Miller et al. 2012). In the past decade, several studies have tracked the microbial community change of entire water distribution systems using high throughput sequencing technology (Ma et al. 2020; Perrin et al. 2019). System-scale community microbiology data has shown clear seasonal trends in microbial drinking water taxa. This study utilized similar genomic methods to characterize the planktonic (free-floating) microbial community in the drinking water of the North Shore Water Commission distribution system, just north of Milwaukee, Wisconsin.\
:::

::: indent
As treated water moves through a pipe system, residual microbes from the source water may multiply, or microbes may enter the flowing water from the biofilm covering the pipe wall (Rittman and Snoeyink 1984). American treatment plants seek to deactivate all microbes in the finished water; whereas, European systems focus on removing nutrients from the finished water, especially ammonia, manganese, and dissolved oxygen: As a result, microbes sloughing from the biofilm tend to regrow quicker in American systems, i.e., the water is more unstable, than microbial growth in European systems.\
:::

::: indent
The overall effect of retention time, or water age, on microbial communities is not clearly understood in American or European systems. As disinfectant residuals decline, and exposure to pipe biofilms rises, microbial regrowth and microbial deposition are hypothesized to cause the total microbial load to rise (Wang et al. 2014). Furthermore, certain taxa such as Sphingomonas, Nitrospira, Mycobacterium, and Hyphomicrobium, have been shown to positively correlate to water age (Chan et al. 2019). However, because water age (retention time) is typically only inferred from spatial data, greater precision in water age measurements will help to characterize microbial community changes with age, and thus improve the understanding of engineering design that impact potential health risks. For example, by identifying regions of a distribution system with chronically high water age, engineers could schedule more frequent hydrant flushing to prevent biofilm formation.\
:::

::: indent
Elucidating water age is a difficult task: Hydrologic models can be used to estimate water age; however, few drinking water systems have models, and those that exist are rarely calibrated with chemical tracers and are based on several untested assumptions (Waples et al. 2015). This study employed a newly designed protocol to measure water age using naturally-occurring radionuclides (Waples et al. 2015). These temporal data combined with 16S rRNA gene sequencing offer insights into microbial growth in a full-scale drinking water system.
:::

## Data Analysis and Results

Click on any of the links to see how each dataset was analyzed. \

<br><br>

::: fake-h2
1. [Water Chemistry and Microbiology](water-chemistry-and-microbiology.html) \
:::

<br><br>

::: fake-h2
2. [Radiochemistry](radiochemistry.html) \
:::

<br><br>

::: fake-h2
3. [Modeling](modeling.html) \
:::

<br><br><br>

## Conclusion

::: indent
At the spatial scale studied (0 - 5.8 km from the treatment plant), the microbial community\ correlates weakly with water age. Following water treatment, a community of lake microbes\ remained in the pipe system. The flowing water was then seeded by the pipe biofilm near the\ treatment plant, and a core group of microbes was established. Past studies have observed a\ similar trend: Researchers have hypothesized that the bulk water is seeded by microbes close to\ the treatment plant, and that this community determines the core microbiome. Furthermore, many studies have found a consistent core community that is relatively\ constant throughout distribution systems. After\ becoming established, the core community has been shown to remain stable until sampling\ points are separated by > 46 km. Water age at any particular site tended to\ vary more than expected, ranging from 25.3 – 49.58 hours at station 4, and 58.0 – 96.6 hours at\ station 5, indicating that water age is loosely correlated to pipe distance. A seasonal increase in\ water age, likely associated with decreased lawn maintenance, was also observed.\ 
:::

::: indent 
Evidently, a reservoir of unsupported ^90^Y exists in the pipe system near the treatment\ plant. The reservoir is likely bound to the pipe scale, sloughing at stochastic rates. To minimize\ the likelihood of sloughing, future studies should either flush the hydrants for long periods of\ time (> 10 minutes), or sample domestic taps. Long flushing times will not substantially alter the\ location from which water was sampled because the volume of flushed water is significantly\ lower than the volume of water within the pipe system.
:::



::: fake-h2
Contact
:::

If you have any questions or feedback, feel free to reach out to me at [spehlmannm\@icloud.com](mailto:spehlmannm@icloud.com).

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>

<script src = "custom.js"> </ script>